/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Yossy
 */
public class Ventana extends javax.swing.JFrame {

    private Jugador banca = new Jugador("Banca");
    private Jugador jugador = new Jugador(JOptionPane.showInputDialog(this,"¿Cómo te llamas?","Nuevo Jugador",3));
    private TipoDeBaraja baraja;
    private Partida partida;
    private boolean jugando=false;

    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoBaraja = new javax.swing.JComboBox<>();
        jbNuevaPartida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpBanca = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpJugador = new javax.swing.JPanel();
        jbPedir = new javax.swing.JButton();
        jbPlantarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlJugador = new javax.swing.JLabel();
        jlBanca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecciona Juego:");

        cbTipoBaraja.setModel(new DefaultComboBoxModel<String>(TipoDeBaraja.nombresBaraja()));
        cbTipoBaraja.setSelectedItem(null);
        cbTipoBaraja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoBarajaActionPerformed(evt);
            }
        });

        jbNuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaes/0otra_partida.png"))); // NOI18N
        jbNuevaPartida.setText("Nueva Partida");
        jbNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaPartidaActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Banca"));
        jScrollPane1.setForeground(new java.awt.Color(51, 153, 0));

        jpBanca.setBackground(new java.awt.Color(102, 153, 0));
        jpBanca.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jpBanca);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(jugador.getNombre()));
        jScrollPane2.setForeground(new java.awt.Color(51, 153, 0));

        jpJugador.setBackground(new java.awt.Color(102, 153, 0));
        jpJugador.setLayout(new java.awt.GridBagLayout());
        jScrollPane2.setViewportView(jpJugador);

        jbPedir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaes/0mas.png"))); // NOI18N
        jbPedir.setText("Pedir Carta");
        jbPedir.setEnabled(false);
        jbPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedirActionPerformed(evt);
            }
        });

        jbPlantarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaes/0stop.png"))); // NOI18N
        jbPlantarse.setText("Plantarse");
        jbPlantarse.setEnabled(false);
        jbPlantarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlantarseActionPerformed(evt);
            }
        });

        jLabel2.setText("Puntos Banca:");

        jLabel3.setText("Puntos Jugador:");

        jlJugador.setText("0");

        jlBanca.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipoBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jlBanca))
                            .addComponent(jbPedir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(98, 98, 98)
                                .addComponent(jlJugador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jbNuevaPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jbPlantarse)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPedir)
                    .addComponent(jbPlantarse)
                    .addComponent(jbNuevaPartida))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlBanca)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jlJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoBarajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoBarajaActionPerformed
        mNuevaPartida();
    }//GEN-LAST:event_cbTipoBarajaActionPerformed

    private void jbNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaPartidaActionPerformed
        if(jugando){
            int respuesta=JOptionPane.showOptionDialog(
                    this, "La partida no ha terminado, ¿seguro que quieres comenzar otra?",
                    "¿Fin de la partida?", JOptionPane.YES_NO_OPTION, 2, null, null, null);
            if (respuesta==0)mNuevaPartida();
        }else{
        mNuevaPartida();
        }
    }//GEN-LAST:event_jbNuevaPartidaActionPerformed

    private void jbPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedirActionPerformed
        Carta siguiente = partida.obtenerOtraCarta();
        JLabel carta = new JLabel(new ImageIcon(this.getClass().getResource(partida.imagenCarta() + siguiente.getImagen())));
        jpJugador.add(carta);
        jpJugador.revalidate();
        jlJugador.setText(Float.toString(jugador.devuelveSumaCartas()));
        jugando=true;
        darResultados();
    }//GEN-LAST:event_jbPedirActionPerformed

    private void jbPlantarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlantarseActionPerformed
        plantarse();
        partida.isJugador = false;
        while (partida.comprobarCondicionVictoria()==null) {
            Carta siguiente = partida.obtenerOtraCarta();
            JLabel carta = new JLabel(new ImageIcon(this.getClass().getResource(partida.imagenCarta() + siguiente.getImagen())));
            jpBanca.add(carta);
            jpBanca.revalidate();
            jlBanca.setText(Float.toString(banca.devuelveSumaCartas()));
            darResultados();
        }
        jugando=false;
    }//GEN-LAST:event_jbPlantarseActionPerformed

    public void darResultados() {
        if (partida.comprobarCondicionVictoria() != null) {
            JOptionPane.showMessageDialog(this, partida.comprobarCondicionVictoria());
            plantarse();
        }else if (partida.isJugador==false)
            JOptionPane.showMessageDialog(this,"La banca saca carta");
    }

    public void mNuevaPartida() {
        try {
            this.baraja = TipoDeBaraja.devuelveBaraja((String) cbTipoBaraja.getSelectedItem());
            partida = new Partida(banca, jugador, baraja);
            jugador.setPuntos(0f);
            banca.setPuntos(0f);
            jpBanca.removeAll();
            jpJugador.removeAll();
            jbPedir.setEnabled(true);
            jbPlantarse.setEnabled(true);
            jpBanca.repaint();
            jpJugador.repaint();
            jlBanca.setText(Float.toString(banca.devuelveSumaCartas()));
            jlJugador.setText(Float.toString(jugador.devuelveSumaCartas()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una baraja");
        }
    }

    public void plantarse() {
        jbPedir.setEnabled(false);
        jbPlantarse.setEnabled(false);
        jugando=false;
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipoBaraja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbNuevaPartida;
    private javax.swing.JButton jbPedir;
    private javax.swing.JButton jbPlantarse;
    private javax.swing.JLabel jlBanca;
    private javax.swing.JLabel jlJugador;
    private javax.swing.JPanel jpBanca;
    private javax.swing.JPanel jpJugador;
    // End of variables declaration//GEN-END:variables
}
